export const compras = [
  {
    id: 1,
    codeSeat: "A7",
    idCity: 1,
    idCinema: 2,
    idSala: 2,
    idFuncion: 2,
    date: "16 de mayo",
    hour: "11:00",
  },
  {
    id: 1,
    codeSeat: "A8",
    idCity: 1,
    idCinema: 2,
    idSala: 2,
    idFuncion: 2,
    date: "16 de mayo",
    hour: "11:00",
  },
  {
    id: 1,
    codeSeat: "A9",
    idCity: 1,
    idCinema: 2,
    idSala: 2,
    idFuncion: 2,
    date: "16 de mayo",
    hour: "11:00",
  },
  {
    id: 1,
    codeSeat: "B7",
    idCity: 1,
    idCinema: 2,
    idSala: 2,
    idFuncion: 2,
    date: "16 de mayo",
    hour: "11:00",
  },
  {
    id: 1,
    codeSeat: "B7",
    idCity: 1,
    idCinema: 2,
    idSala: 2,
    idFuncion: 2,
    date: "16 de mayo",
    hour: "13:00",
  },
];
